### ISSUE TITLE
Test caused an  error

### ISSUE THREAD

**Issue by JunjiUmeno** [spring-guides/gs-reactive-rest-service#13]
I had such an error on the test that 'Cant autowire `WebTestClient` - no auto configuration'. It was resolved with a post on Stackoverflow.

[stackoverflow post](https://stackoverflow.com/questions/48226651/cant-autowire-webtestclient-no-auto-configuration)

**Comment by dsyer** [comment]
Works for me. What did you do exactly?

**Comment by bclozel** [comment]
Closing due to lack of feedback.
