### ISSUE TITLE
Code samples missing from reactive-rest-service guide (Unresolved directive in <stdin> - include::complete/...)

### ISSUE THREAD

**Issue by starcatter** [spring-guides/gs-reactive-rest-service#17]
In the code preview windows I only see text saying there was a problem including the file, like
`Unresolved directive in <stdin> - include::complete/src/main/java/hello/GreetingRouter.java[]`

I'm getting this in all code boxes, there's different file names in error messages.

example:
![image](https://user-images.githubusercontent.com/30572485/75614541-17939480-5b3a-11ea-8927-89fbc948acc2.png)

**Comment by dsyer** [comment]
Looks OK to me. I think it was a stale cache. Thanks for reporting the problem.

**Comment by james-yun** [comment]
Getting this same error
https://spring.io/guides/gs/reactive-rest-service/

**Comment by dsyer** [comment]
Fixed again (cleared cache). There are some other errors, but unrelated.

**Comment by ophiuhus** [comment]
Hey, it looks like issue happened again
https://spring.io/guides/gs/reactive-rest-service
