### ISSUE TITLE
result is null

### ISSUE THREAD

**Issue by WorksOnMyVM** [spring-guides/gs-reactive-rest-service#18]
console logs 
`2020-04-30 15:51:26.861  WARN 76075 --- [nio-8080-exec-1] c.f.c.c.BeanFactoryAwareFunctionRegistry : !!! Failed to discover function 'hello' in function catalog. Function available in catalog are: [functionRouter]
`
 result prints

`>> result = null`

**Comment by bclozel** [comment]
`BeanFactoryAwareFunctionRegistry` belongs to Spring Cloud Function, and this repository is not using it. I'm assuming you've created this issue against the wrong repository.
