### ISSUE TITLE
Broken link for source code files

### ISSUE THREAD

**Issue by chinmoy12c** [spring-guides/gs-reactive-rest-service#25]
The links pointing to the source files [here](https://spring.io/guides/gs/reactive-rest-service/#:~:text=or%20other%20editor.-,Create%20a%20WebFlux%20Handler,-We%E2%80%99re%20going%20to) seems to be broken after the recent package renaming.

**Comment by AlbertSnows** [comment]
+1, came here to make this very issue

**Comment by AlbertSnows** [comment]
In the meantime if anyone else comes here you can find the files in this directory.
https://github.com/spring-guides/gs-reactive-rest-service/tree/main/complete/src/main/java/com/example/reactivewebservice

**Comment by Buzzardo** [comment]
That was my fault. I made the paths match what the Spring Initializr produces and forgot to check the readme file. Thanks for catching it.
