### ISSUE TITLE
404 using code from the complete folder

### ISSUE THREAD

**Issue by andrewoh531** [spring-guides/gs-reactive-rest-service#6]
Followed the instructions from here: https://spring.io/guides/gs/reactive-rest-service/#initial

Then I downloaded the zipped version of the code and tried running it but got the same error (below) when attempting to hit `http://localhost:8080/hello`

```

 Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
OPTIONS                                                    | GET                                                 <<<<< HTTP method does not match
(always)                                                   | /hello                                              <<<<< null. URLs must start with a /
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

**Comment by dsyer** [comment]
Works for me. Where did that error come from? Is it the HTTP client you are using?

**Comment by andrewoh531** [comment]
It's what the client receives. I tried it in chrome browser, POSTMAN and also the client from the example: https://spring.io/guides/gs/reactive-rest-service/#_create_a_webclient

**Comment by dsyer** [comment]
I guess you didn't run the same code as me then. Forget POSTMAN. Just run the app:

```
$ mvn spring-boot:run
...
2018-05-21 11:31:58.604  INFO 12390 --- [           main] hello.Application                        : Started Application in 1.225 seconds (JVM running for 3.012)
>> result = Hello, Spring!
...
```

If that doesn't work, check your Maven cache, and your network connection.

**Comment by andrewoh531** [comment]
That didn't work so I rebooted and it's fixed the issue...strange...I thought reboots were only required on Windoze...

Thanks!

**Comment by andrewoh531** [comment]
Re-opening to see if further diagnosis can be applied. 

The problem has resurfaced. I am beginning to wonder if there is a bug somewhere in the framework. I'm getting a 404 so I'm assuming the server is receiving the request but not finding the route. 

Is there something I can enable to further debug the issue? I enabled `debug=true` in the `application.properties` but didn't see anything interesting in the logs.

**Comment by dsyer** [comment]
It still works for me. You are going to have to post some more logs or a stack trace or something. How about `logging.level.ROOT=debug`?

**Comment by gregturn** [comment]
Dave,

What if there is a race condition between the container coming up and registering the handler vs the client gearing up to make a Web call?

@mp911de and @snicoll have mentioned certain scenarios that can result in deadlocks with WebFlux. A locked up thread that requires reboot could be a symptom.

If we could hold off making the web call until the app context says it’s up, maybe we could dodge this.

**Comment by rhsudo** [comment]
I can confirm the 404 error when running this application.

It works fine in the browser. When you navigate to `/hello` you do see `Hello, Spring!`.

But when you run either `./gradlew bootRun` or `./mvnw spring-boot:run`, you get this output:

```bash
>> result = <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.2</center>
</body>
</html>
```

I set `logging.level.ROOT=debug` and dumped it into a [gist](https://gist.github.com/roberthamel/236c65ea85e55522ef55259392d5629b). Hope that helps.

**Comment by dsyer** [comment]
The HTML response there says it is from nginx (which isn’t part of this guide). I suspect you have something running on port 8080.

**Comment by rhsudo** [comment]
Stopping the running nginx Homebrew service did fix it. What confused me was that fact that it still worked in the browser, but not the command line.
